-- UPDATE 실습 --
UPDATE department2 SET dept_title = '인사팀'
WHERE DEPT_ID = 'D1';

UPDATE DEPARTMENT2 SET DEPT_TITLE = '마케팅팀'
WHERE DEPT_ID = 'D3';

UPDATE DEPARTMENT2 SET DEPT_TITLE = '기술지원팀'
WHERE DEPT_ID = 'D8';

SELECT * FROM DEPARTMENT2;

COMMIT;

UPDATE EMPLOYEE2 SET BONUS = 0.1
WHERE BONUS IS NULL;

SELECT EMP_NAME,BONUS FROM EMPLOYEE2;

ROLLBACK;

UPDATE EMPLOYEE2 SET SALARY = salary + 500000;

UPDATE EMPLOYEE2 SET BONUS = 0.4
WHERE DEPT_CODE = 'D9';

SELECT DEPT_CODE,BONUS FROM EMPLOYEE2;

UPDATE EMPLOYEE2 SET DEPT_CODE = 'D3'
WHERE DEPT_CODE IS NULL;

UPDATE EMPLOYEE2 SET salary = SALARY - 500000
WHERE HIRE_DATE > TO_DATE('2000-01-01', 'YYYY-MM-DD');

UPDATE EMPLOYEE2 SET ent_yn = 'Y'
WHERE hire_date = TO_DATE('1997-09-12', 'YYYY-MM-DD');

ROLLBACK; -- UPDATE 모두 취소

UPDATE employee2 SET EMAIL = REPLACE(EMAIL,'or.kr','kh.kh');

SELECT EMAIL FROM employee2;

UPDATE EMPLOYEE2 SET PHONE = REPLACE(PHONE,'010','010-')
WHERE PHONE LIKE '010%';
/*
"EMPLOYEE2"."PHONE" (actual: 13, maximum: 12
    -> 행 최대 크기를 12자리로 설정해뒀기 때문에 나중에 발생하는 에러
    -> 행 최대 크기를 늘리거나 ROLLBACK 실행
*/
SELECT PHONE FROM EMPLOYEE2;

UPDATE EMPLOYEE2 SET HIRE_DATE = TO_DATE('2000-01-02', 'YYYY-MM-DD')
WHERE HIRE_DATE = TO_DATE('1999-09-09', 'YYYY-MM-DD');

SELECT HIRE_DATE FROM EMPLOYEE2;

COMMIT;

SELECT * FROM department2;

UPDATE department2 SET DEPT_TITLE = '인사팀';

SELECT * FROM department2;

ROLLBACK;

UPDATE EMPLOYEE3 SET SALARY = SALARY * 1.1, BONUS = 0.2
WHERE DEPT_CODE = 'D9';

UPDATE EMPLOYEE3 SET JOB_CODE = 'J5', DEPT_CODE = 'D5'
WHERE JOB_CODE = 'J3';

UPDATE EMPLOYEE3 SET EMP_NAME = '송은휘', EMAIL = 'SONGSONG@or.kr'
WHERE EMP_NAME = '송은희';

ROLLBACK;

UPDATE EMPLOYEE3 SET EMP_NAME = '차태형', SALARY = 8000000
WHERE EMP_NAME = '차태연';

UPDATE EMPLOYEE3 SET EMAIL = REPLACE(EMAIL, 'or.kr', 'google.com'), DEPT_CODE = 'D4';

SELECT * FROM EMPLOYEE3;

ROLLBACK;

-- EMPLOYEE3 전체 테이블 삭제
DELETE FROM EMPLOYEE2;
-- 완전 삭제 -> COMMIT
-- 되돌리기(복구) -> ROLLBACK
COMMIT;

SELECT * FROM EMPLOYEE2;

DROP TABLE EMPLOYEE3; -- 테이블 자체를 삭제

COMMIT;


