/* JOIN 실습 */
SELECT EMP_NAME,DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);

SELECT EMP_NAME,DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

SELECT EMP_NAME,DEPT_TITLE,SALARY
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);

SELECT EMP_NAME,DEPT_TITLE,SALARY
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

SELECT EMP_NAME,employee.SAL_LEVEL
FROM EMPLOYEE
JOIN SAL_GRADE ON (employee.SAL_LEVEL = sal_GRADE.SAL_LEVEL);
/*
다른 테이블에서 컬렴명은 다르지만 서로 의미하는 바가 같은 컬럼끼리는
컬럼명 1 = 컬럼명2  사용할 수 있음

다른 테이블에서 컬럼명이 같은 때는 참조하는 테이블이 무엇인지 작성해줘야함
테이블명.컬럼명1 = 테이블명.컬럼명2
*/

SELECT EMP_NAME,e.SAL_LEVEL
FROM EMPLOYEE e, SAL_GRADE s
WHERE e.SAL_LEVEL = s.SAL_LEVEL;

-- 각 직원의 이름과 그 직원이 속한 부서의 부서명 및 직급 조회
SELECT e.EMP_NAME,d.DEPT_TITLE,j.JOB_NAME
FROM EMPLOYEE e
JOIN DEPARTMENT d ON(e.DEPT_CODE = d.DEPT_ID)
JOIN JOB j ON (e.JOB_CODE = j.JOB_CODE);

SELECT EMP_NAME,DEPT_TITLE,JOB_NAME
FROM EMPLOYEE e, DEPARTMENT d, JOB J
WHERE DEPT_CODE = DEPT_ID AND e.JOB_CODE = j.JOB_CODE;

-- 직원의 이메일 주소와 해당 부서의 부서명 조회
SELECT EMAIL, DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);

SELECT EMAIL, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

-- 급여가 300만원 이상인 직원들의 이름과 그 직원이 속한 부서명 조회
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE SALARY >= 3000000;

SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE SALARY >= 3000000 AND DEPT_CODE = DEPT_ID;

-- 각 직원의 이름과 그 직원이 속한 부서명, 급여 등급명 조회
SELECT EMP_NAME, d.DEPT_TITLE, e.SAL_LEVEL
FROM EMPLOYEE e
JOIN DEPARTMENT d ON (DEPT_CODE = DEPT_ID)
JOIN SAL_GRADE s ON (e.SAL_LEVEL = s.SAL_LEVEL);

SELECT EMP_NAME, DEPT_TITLE, s.SAL_LEVEL
FROM EMPLOYEE e, DEPARTMENT, SAL_GRADE s
WHERE DEPT_CODE = DEPT_ID AND e.SAL_LEVEL = s.SAL_LEVEL;

-- 직급이 대리이면서 아시아지역에 근무하는 직원
-- 사번, 이름, 직급이름, 부서이름, 근무지역, 월급 조회
SELECT EMP_ID, EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME, SALARY
FROM EMPLOYEE e
JOIN DEPARTMENT d ON (e.DEPT_CODE = d.DEPT_ID)
JOIN JOB j ON (e.JOB_CODE = j.JOB_CODE)
JOIN LOCATION l ON (d.LOCATION_ID = l.LOCAL_CODE)
WHERE j.JOB_NAME = '대리' AND l.LOCAL_NAME LIKE 'ASIA%';

SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME, D.DEPT_TITLE, L.LOCAL_NAME, E.SALARY
FROM EMPLOYEE E, DEPARTMENT D, JOB J, LOCATION L
WHERE E.DEPT_CODE = D.DEPT_ID AND E.JOB_CODE = J.JOB_CODE AND
D.LOCATION_ID = L.LOCAL_CODE AND J.JOB_NAME = '대리' AND 
L.LOCAL_NAME LIKE 'ASIA%';

-- D5 부서에 속한 직원들의 이름과 직급명 조회
SELECT EMP_NAME, JOB_NAME
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE DEPT_CODE = 'D5';

SELECT E.EMP_NAME, J.JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE AND DEPT_CODE = 'D5';

-- 각 부서의 부서명과 해당 부서에 속한 직원의 평균 급여 조회
SELECT DEPT_TITLE, AVG(SALARY)
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
GROUP BY DEPT_TITLE;

SELECT DEPT_TITLE, FLOOR(AVG(SALARY))
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID
GROUP BY DEPT_TITLE;

--  급여 등급이 S4 이상인 직원의 이름, 급여, 급여 등급 조회
SELECT * FROM SAL_GRADE;

SELECT EMP_NAME,SALARY,SAL_LEVEL
FROM EMPLOYEE
JOIN SAL_GRADE USING(SAL_LEVEL)
WHERE SAL_LEVEL IN ('S4', 'S5', 'S6');

SELECT EMP_NAME,SALARY,S.SAL_LEVEL
FROM EMPLOYEE E, SAL_GRADE S
WHERE E.SAL_LEVEL = S.SAL_LEVEL AND S.SAL_LEVEL IN ('S4','S5','S6');



















