/* CREATE TABLE 실습 */
-- 고객테이블 CUSTOMER
CREATE TABLE CUSTOMER(
CUSTOMER_ID NUMBER(10,0) PRIMARY KEY,
CUSTOMER_NAME VARCHAR2(100) NOT NULL,
CUSTOMER_EMAIL VARCHAR2(100) CONSTRAINT C_E_U UNIQUE,
CUSTOMER_PHONE VARCHAR2(20),
CONSTRAINT C_P_U UNIQUE(CUSTOMER_PHONE),
CUSTOMER_ADDRESS VARCHAR2(255)
);

COMMENT ON COLUMN CUSTOMER.CUSTOMER_ID IS '고객아이디';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_NAME IS '고객이름';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_EMAIL IS '고객이메일';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_PHONE IS '고객휴대폰';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_ADDRESS IS '고객주소';
/*
ORA-01780: string literal required
01780. 00000 -  "string literal required"
-> 큰 따옴표 문제
*/
COMMIT;

-- PRODUCT 테이블 생성
CREATE TABLE PRODUCT(
    PRODUCT_ID NUMBER(10,0) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    PRODUCT_PRICE NUMBER(10,2) NOT NULL,
    PRODUCT_DESC VARCHAR2(200) CONSTRAINT P_D_U UNIQUE
);
COMMIT;

INSERT INTO PRODUCT VALUES (1, '아메리카노',3000,'신선한 원두로 만든 아메리카노');
INSERT INTO PRODUCT VALUES (2, '카페라떼',2500,'부드러운 우유가 들어간 라떼');
INSERT INTO PRODUCT VALUES (3, '카푸치노',3500,'진한 커피와 거품이 어우러진 카푸치노');
INSERT INTO PRODUCT VALUES (4, '카라멜 마키야토',4000,'달콤한 카라멜 시럽이 들어간 마키야토');

-- FOOD_COMPANY TABLE 생성
CREATE TABLE FOOD_COMPANY(
    COMPANY_ID NUMBER(10,0) PRIMARY KEY, -- 회사 ID 기본키
    COMPANY_NAME VARCHAR2(100) NOT NULL, -- 회사 이름 NULL 불가
    COMPANY_ADDRESS VARCHAR2(255), -- 회사 주소
    COMPANY_PHONE VARCHAR2(20) -- 회사 전화번호
);

-- SNACKS 테이블 생성
CREATE TABLE SNACTK(
    SNACKS_ID NUMBER(10,0) PRIMARY KEY, -- 과자 ID 기본키
    SNACKS_NAME VARCHAR2(100) NOT NULL, -- 과자 이름 NULL 불가
    PRICE NUMBER(10,2) NOT NULL, -- 과자 가격 NULL 불가
    COMPANY_ID NUMBER(10,0),
    CONSTRAINT FK_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES FOOD_COMPANY(COMPANY_ID) ON DELETE CASCADE
);
-- ORA-00904 : COMPANY_ID NUMBER(10,0)

CREATE TABLE SNACTK1(
    SNACKS_ID NUMBER(10,0) PRIMARY KEY, -- 과자 ID 기본키
    SNACKS_NAME VARCHAR2(100) NOT NULL, -- 과자 이름 NULL 불가
    PRICE NUMBER(10,2) NOT NULL, -- 과자 가격 NULL 불가
    CCCCCCCCC NUMBER(10,0),
    CONSTRAINT FK_COMPANY1 FOREIGN KEY (CCCCCCCCC) REFERENCES FOOD_COMPANY(COMPANY_ID) ON DELETE CASCADE
);

CREATE TABLE SNACTK2(
    SNACKS_ID NUMBER(10,0) PRIMARY KEY, -- 과자 ID 기본키
    SNACKS_NAME VARCHAR2(100) NOT NULL, -- 과자 이름 NULL 불가
    PRICE NUMBER(10,2) NOT NULL, -- 과자 가격 NULL 불가
    AAAAAA NUMBER(10,0),
    CONSTRAINT FK_COMPANY2 FOREIGN KEY (AAAAAA) REFERENCES FOOD_COMPANY(COMPANY_ID) ON DELETE CASCADE
);

CREATE TABLE SNACTK3(
    SNACKS_ID NUMBER(10,0) PRIMARY KEY, -- 과자 ID 기본키
    SNACKS_NAME VARCHAR2(100) NOT NULL, -- 과자 이름 NULL 불가
    PRICE NUMBER(10,2) NOT NULL, -- 과자 가격 NULL 불가
    ABCEDF NUMBER(10,0),
    CONSTRAINT FK_COMPANY3 FOREIGN KEY (ABCEDF) REFERENCES FOOD_COMPANY(COMPANY_ID) ON DELETE CASCADE
);
--> ABCDEF FOREIGN KEY 키를 참조할 변수명
--> 참조할 변수명 FK_COMPANY3 규칙명 작성해주는데 규칭명은 모든 테이블 합쳐서 동일한 이름을 쓸 수 없음

-- 테이블 생성 DRINK_COMPANY
CREATE TABLE DRINK_COMPANY(
    DRINK_ID NUMBER(10,0) PRIMARY KEY,
    DRINK_NAME VARCHAR2(100) NOT NULL,
    DRINK_ADDRESS VARCHAR2(255),
    DRINK_PHONE VARCHAR2(20)
);

-- 테이블 생성 SOFTS
CREATE TABLE SOFTS(
    SOFTS_ID NUMBER(10,0) PRIMARY KEY,

);







