/* 지금부터 만드는 것은 KH_WORKBOOK 이라는 곳에 만들 테이블 생성 */
CREATE TABLE COMPANY (
    COMPANY_ID NUMBER PRIMARY KEY,
    COMPANY_NAME VARCHAR(100) NOT NULL,
    COMPANY_ADDRESS VARCHAR2(55),
    COMPANY_PHONE VARCHAR2(20)
);

-- COMPANY 테이블명 ALTER 사용하여 COM 으로 변경
ALTER TABLE COMPANY RENAME TO COM;

SELECT * FROM COM;

-- COM 시퀀스 생성
-- 시퀀스명 COM_SEQ 시작값 1(기본값) 증가값 1(기본값) NOCACHE(기본값) NOCYCLE(기본값)
-- 방법 1
CREATE SEQUENCE COM_SEQ;

-- 방법 2
CREATE SEQUENCE COM_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE
;

-- INSERT COM 회사 추가
INSERT INTO COM VALUES (com_seq.nextval, '헷에제과','서울시 강남구','02-1234-5678');

-- NEXTVAL 이용해서 회사 추가
INSERT INTO COM VALUES (com_seq.nextval, '롯에제가','서울시 중구','02-2345-6789');
INSERT INTO COM VALUES (com_seq.nextval, '올이온','서울시 용산구','02-3456-7890');

SELECT * FROM COM;

CREATE TABLE SNACKS (
    SNACK_ID NUMBER(10,0),
    SNACK_NAME VARCHAR2(100),
    PRICE NUMBER(10,2),
    COMPANY_ID NUMBER(10,0),
    CONSTRAINT COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COM(COMPANY_ID) ON DELETE CASCADE
);

SELECT * FROM COM;
SELECT * FROM SNACKS;

-- SNACKS_SEQ 시퀀스 생성
CREATE SEQUENCE SNACKS_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE
;

-- SNACKS_SEQ NEXTVAL 이용해서 INSERT 
INSERT INTO SNACKS VALUES (snacks_seq.nextval,'오에스',1500,'1');
INSERT INTO SNACKS VALUES (snacks_seq.nextval,'칸조',1220,'1');
INSERT INTO SNACKS VALUES (snacks_seq.nextval,'배배로',1100,'2');
INSERT INTO SNACKS VALUES (snacks_seq.nextval,'조고파이',2000,'2');

SELECT * FROM SNACKS;

-- 가격이 1500 이상인 과자 조회
SELECT * FROM SNACKS
WHERE PRICE >= 1500;

-- 서울시 강남구에 위치한 회사 조회
SELECT * FROM COM
WHERE COMPANY_ADDRESS LIKE '%강남구%';

-- 회사 ID 가 1인 과자 조회
SELECT * FROM SNACKS
WHERE COMPANY_ID = 1;

-- 회사 ID 가 1이고, 그 회사의 과자들 조회(JOIN)
SELECT C.COMPANY_ID, SNACK_NAME
FROM COM C
JOIN SNACKS S ON (C.COMPANY_ID = S.COMPANY_ID)
WHERE C.COMPANY_ID = 1;

SELECT COMPANY_ID, SNACK_NAME
FROM COM
JOIN SNACKS USING(COMPANY_ID)
WHERE COMPANY_ID = 1;

SELECT C.COMPANY_ID,c.company_name, SNACK_NAME
FROM COM C, SNACKS S
WHERE c.company_id = s.company_id
AND c.company_id = 1;

















