-- 1
SELECT EMP_NAME,EMP_NO,DEPT_TITLE,JOB_NAME
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE E.DEPT_CODE = D.DEPT_ID 
AND E.JOB_CODE = J.JOB_CODE
AND SUBSTR(EMP_NO,8,1) = '2'
AND EMP_NAME LIKE '전%';
-- 2
SELECT EMP_ID, EMP_NAME, JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE
AND EMP_NAME LIKE '%형%';
-- 3
SELECT EMP_NAME,JOB_NAME,DEPT_CODE,DEPT_TITLE
FROM EMPLOYEE E, JOB J, DEPARTMENT D
WHERE E.JOB_CODE = J.JOB_CODE
AND E.DEPT_CODE = D.DEPT_ID
AND D.DEPT_TITLE LIKE '해외영업%';
-- 4
SELECT EMP_NAME,BONUS,DEPT_TITLE,LOCAL_NAME
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L
WHERE E.DEPT_CODE = D.DEPT_ID
AND D.LOCATION_ID = L.LOCAL_CODE
AND BONUS IS NOT NULL;
-- 5
SELECT EMP_NAME,JOB_NAME,DEPT_TITLE,LOCAL_NAME
FROM EMPLOYEE E, DEPARTMENT D, JOB J, LOCATION L
WHERE E.DEPT_CODE = D.DEPT_ID
AND E.JOB_CODE = J.JOB_CODE
AND D.LOCATION_ID = L.LOCAL_CODE
AND DEPT_CODE IS NOT NULL;
-- 6
SELECT EMP_NAME,JOB_NAME,SALARY,SALARY*12*(1+NVL(BONUS,'0')) AS "연봉"
FROM EMPLOYEE E, JOB J, SAL_GRADE S
WHERE E.JOB_CODE = J.JOB_CODE
AND E.SAL_LEVEL = S.SAL_LEVEL
AND SALARY > S.MIN_SAL;
-- 7
SELECT EMP_NAME AS "사원명",DEPT_TITLE AS "부서명",LOCAL_NAME AS "지역명",NATIONAL_NAME AS "국가명"
FROM EMPLOYEE E, DEPARTMENT D,LOCATION L, NATIONAL N
WHERE E.DEPT_CODE = D.DEPT_ID
AND D.LOCATION_ID = L.LOCAL_CODE
AND L.NATIONAL_CODE = N.NATIONAL_CODE
AND n.national_name IN ('한국', '일본');
-- 8
SELECT E.EMP_NAME AS "사원명", E.DEPT_CODE AS "부서코드", A.EMP_NAME AS "동료이름"
FROM EMPLOYEE E
JOIN EMPLOYEE A ON(E.DEPT_CODE = A.DEPT_CODE)
WHERE E.DEPT_CODE IS NOT NULL
AND E.EMP_NAME != A.EMP_NAME
ORDER BY 1;
-- 9
SELECT EMP_NAME,JOB_NAME,SALARY
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE
AND BONUS IS NULL
AND E.JOB_CODE IN ('J4', 'J7');






















