SELECT DEPT_TITLE,DEPT_ID,LOCATION_ID
FROM DEPARTMENT
ORDER BY DEPT_TITLE;

SELECT *
FROM EMPLOYEE
ORDER BY SALARY DESC;

SELECT EMP_NAME,HIRE_DATE FROM EMPLOYEE
ORDER BY HIRE_DATE;

SELECT LOCAL_NAME FROM LOCATION
ORDER BY NATIONAL_CODE;

SELECT EMP_ID,EMP_NAME FROM EMPLOYEE
ORDER BY EMP_NAME;

SELECT DEPT_CODE,AVG(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING AVG(SALARY) > 3000000;

SELECT JOB_CODE,COUNT(EMP_ID)
FROM EMPLOYEE
GROUP BY JOB_CODE
HAVING COUNT(EMP_ID) >= 3;

SELECT DEPT_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING SUM(SALARY) >= 10000000;

SELECT SAL_LEVEL,MAX(SALARY)
FROM EMPLOYEE
GROUP BY SAL_LEVEL
HAVING MAX(SALARY) < 5000000;

SELECT DEPT_CODE,MIN(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING MIN(SALARY) >= 2000000;

SELECT DEPT_CODE, COUNT(EMP_ID)
FROM EMPLOYEE
GROUP BY DEPT_CODE;

SELECT JOB_CODE, AVG(SALARY)
FROM EMPLOYEE
GROUP BY JOB_CODE;

SELECT SAL_LEVEL, SUM(BONUS)
FROM EMPLOYEE
GROUP BY SAL_LEVEL;

SELECT DEPT_CODE, MAX(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE;

SELECT JOB_CODE, MIN(SALARY)
FROM EMPLOYEE
GROUP BY JOB_CODE;

SELECT NATIONAL_CODE, COUNT(*)
FROM LOCATION
GROUP BY NATIONAL_CODE;

SELECT LOCATION_ID, COUNT(*)
FROM DEPARTMENT
GROUP BY LOCATION_ID;

SELECT DEPT_CODE, AVG(BONUS)
FROM EMPLOYEE
GROUP BY DEPT_CODE;

SELECT SAL_LEVEL, COUNT(*)
FROM EMPLOYEE
GROUP BY SAL_LEVEL;

SELECT JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY JOB_CODE;

SELECT EMP_NAME,SALARY
FROM EMPLOYEE
WHERE SALARY >= 3000000;

SELECT EMP_NAME,DEPT_CODE
FROM EMPLOYEE
WHERE DEPT_CODE = 'D1';

SELECT EMP_NAME,JOB_CODE
FROM EMPLOYEE
WHERE JOB_CODE = 'J2';

SELECT EMP_NAME,SAL_LEVEL
FROM EMPLOYEE
WHERE SAL_LEVEL = 'S4';

SELECT DEPT_TITLE,LOCATION_ID
FROM DEPARTMENT
WHERE LOCATION_ID = 'L1';

SELECT LOCAL_NAME,NATIONAL_CODE
FROM LOCATION
WHERE NATIONAL_CODE = 'US';

SELECT NATIONAL_CODE,NATIONAL_NAME
FROM NATIONAL
WHERE NATIONAL_NAME = '한국';

SELECT SAL_LEVEL, MIN_SAL
FROM SAL_GRADE
WHERE MIN_SAL >= 2000000;

SELECT EMP_NAME,BONUS
FROM EMPLOYEE
WHERE BONUS IS NOT NULL;

SELECT DEPT_ID,DEPT_TITLE
FROM DEPARTMENT
WHERE SUBSTR(DEPT_TITLE,1,2) = '해외';

SELECT EMP_NAME,ENT_YN
FROM EMPLOYEE
WHERE ENT_YN = 'N';

SELECT EMP_NAME,HIRE_DATE
FROM EMPLOYEE
WHERE HIRE_DATE > TO_DATE('2000-01-01', 'YYYY-MM-DD');

SELECT EMP_NAME,PHONE
FROM EMPLOYEE
WHERE SUBSTR(PHONE,1,3) = '010';

SELECT EMP_NAME,EMAIL
FROM EMPLOYEE
WHERE EMAIL LIKE '%@or.kr';
//WHERE SUBSTR(EMAIL,INSTR(EMAIL,'@',1)) = '@or.kr';

SELECT EMP_NAME,MANAGER_ID
FROM EMPLOYEE
WHERE MANAGER_ID IS NULL;

SELECT EMP_NAME,SALARY
FROM EMPLOYEE
WHERE SALARY BETWEEN 2000000 AND 3000000;

SELECT EMP_NAME,JOB_CODE
FROM EMPLOYEE
WHERE JOB_CODE IN ('J5','J6','J7');

SELECT EMP_NAME,DEPT_CODE,JOB_CODE
FROM EMPLOYEE
WHERE DEPT_CODE = 'D1' AND JOB_CODE = 'J7';

SELECT EMP_NAME,SALARY,BONUS
FROM EMPLOYEE
WHERE SALARY >= 3000000 AND BONUS IS NOT NULL;

SELECT EMP_NAME,DEPT_CODE
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5','D6');

SELECT EMP_NAME,HIRE_DATE
FROM EMPLOYEE
WHERE HIRE_DATE < TO_DATE('2000-01-01', 'YYYY-MM-DD');

SELECT EMP_NAME,PHONE
FROM EMPLOYEE
WHERE PHONE IS NULL;

SELECT DEPT_ID,LOCATION_ID
FROM DEPARTMENT
WHERE LOCATION_ID IN ('L1','L2','L3');

SELECT EMP_NAME,SALARY,ENT_YN
FROM EMPLOYEE
WHERE SALARY >= 3000000 AND ENT_YN = 'N';

SELECT EMP_NAME,DEPT_CODE,ENT_DATE
FROM EMPLOYEE
WHERE DEPT_CODE = 'D2' AND ENT_DATE IS NULL;

