CREATE TABLE USERS(
USERID NUMBER PRIMARY KEY,
NAME VARCHAR2(50) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
PASSWORD VARCHAR2(100) NOT NULL,
CREATEDDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE USERS_SEQ;

INSERT INTO USERS 
VALUES(USERS_SEQ.NEXTVAL,'홍길동','HONG@EXAMPLE.COM','PASSWORD123',SYSDATE);

INSERT INTO USERS 
VALUES(USERS_SEQ.NEXTVAL,'김철수','KIM@EXAMPLE.COM','MYPASSWORD',SYSDATE);

INSERT INTO USERS 
VALUES(USERS_SEQ.NEXTVAL,'이영희','LEE@EXAMPLE.COM','SECUREPASS',SYSDATE);

CREATE TABLE BOARD(
    POSTID NUMBER PRIMARY KEY,
    USERID NUMBER, 
    CONSTRAINT USERID_FK FOREIGN KEY(USERID) REFERENCES USERS(USERID),
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT CLOB NOT NULL
);
ALTER TABLE BOARD ADD CREATEDDATE DATE DEFAULT SYSDATE;

CREATE SEQUENCE BOARD_SEQ;

INSERT INTO BOARD
VALUES (board_seq.nextval, 1, '첫번째 게시물','이것은 첫 번째 게시물의 내용입니다.',DEFAULT);

INSERT INTO BOARD
VALUES (board_seq.nextval, 2, '두번째 게시물','이것은 두 번째 게시물의 내용입니다.',DEFAULT);

INSERT INTO BOARD
VALUES (board_seq.nextval, 3, '세번째 게시물','이것은 세 번째 게시물의 내용입니다.',DEFAULT);


























