-- 1
SELECT EMP_ID,EMP_NAME,PHONE,HIRE_DATE,D.DEPT_TITLE
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE WHERE EMP_NAME = '전지연')
AND EMP_NAME != '전지연';

-- 2
SELECT EMP_ID,EMP_NAME,PHONE,SALARY,J.JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE
AND SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE WHERE HIRE_DATE >= TO_DATE('2000-01-01', 'YYYY-MM-DD'));

-- 3
SELECT EMP_ID,EMP_NAME,DEPT_CODE,E.JOB_CODE,DEPT_TITLE,JOB_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE WHERE EMP_NAME = '노옹철')
AND E.JOB_CODE = (SELECT JOB_CODE FROM EMPLOYEE WHERE EMP_NAME ='노옹철')
AND EMP_NAME != '노옹철';

-- 4
SELECT EMP_ID,EMP_NAME,DEPT_CODE,JOB_CODE,HIRE_DATE
FROM EMPLOYEE
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE WHERE HIRE_DATE BETWEEN TO_DATE('2000-01-01','YYYY-MM-DD') AND TO_DATE('2000-12-31','YYYY-MM-DD'))
AND JOB_CODE = (SELECT JOB_CODE FROM EMPLOYEE WHERE HIRE_DATE BETWEEN TO_DATE('2000-01-01','YYYY-MM-DD') AND TO_DATE('2000-12-31','YYYY-MM-DD'));

-- 5
SELECT EMP_ID,EMP_NAME,DEPT_CODE,MANAGER_ID,EMP_NO,HIRE_DATE
FROM EMPLOYEE
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE WHERE SUBSTR(EMP_NO,1,2) = 77 AND SUBSTR(EMP_NO,8,1) = 2)
AND MANAGER_ID = (SELECT MANAGER_ID FROM EMPLOYEE WHERE SUBSTR(EMP_NO,1,2) = 77 AND SUBSTR(EMP_NO,8,1) = 2);

-- 6
SELECT E.EMP_ID,E.EMP_NAME,NVL(D.DEPT_TITLE,'소속없음'),J.JOB_NAME,E.HIRE_DATE
FROM (SELECT EMP_ID,EMP_NAME,DEPT_CODE,JOB_CODE,HIRE_DATE,ROW_NUMBER() OVER(PARTITION BY DEPT_CODE ORDER BY HIRE_DATE ASC) AS RN
      FROM EMPLOYEE WHERE ENT_YN = 'N') E, DEPARTMENT D, JOB J
WHERE E.DEPT_CODE = D.DEPT_ID(+)
AND E.JOB_CODE = J.JOB_CODE
AND RN = 1
ORDER BY HIRE_DATE;

SELECT EMP_NAME,DEPT_CODE,HIRE_DATE, ROW_NUMBER() OVER(PARTITION BY DEPT_CODE ORDER BY HIRE_DATE ASC) AS RN
FROM EMPLOYEE
WHERE ENT_YN = 'N';

-- 7
SELECT E.EMP_ID,E.EMP_NAME,J.JOB_NAME,E.AGE AS "나이",TO_CHAR((SALARY*12)+(SALARY*12*NVL(E.BONUS, '0')), 'L999,999,999') AS "보너스포함연봉"
FROM (SELECT EMP_ID,EMP_NAME,JOB_CODE,TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE),TO_DATE('19'||SUBSTR(EMP_NO,1,2),'YYYY'))/12) AS AGE,BONUS,
      SALARY, ROW_NUMBER() OVER(PARTITION BY JOB_CODE ORDER BY TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE),TO_DATE('19'||SUBSTR(EMP_NO,1,2),'YYYY'))/12)) AS RN
      FROM EMPLOYEE) E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE
AND RN = 1
ORDER BY 나이 DESC;

SELECT EMP_ID,EMP_NAME,JOB_CODE,TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE),TO_DATE('19'||SUBSTR(EMP_NO,1,2),'YYYY'))/12) AS AGE,BONUS,
      SALARY, ROW_NUMBER() OVER(PARTITION BY JOB_CODE ORDER BY TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE),TO_DATE('19'||SUBSTR(EMP_NO,1,2),'YYYY'))/12)) AS RN
FROM EMPLOYEE;


SELECT E1.EMP_ID,E1.EMP_NAME,E1.HIRE_DATE,E1.DEPT_CODE
FROM EMPLOYEE E1
WHERE E1.HIRE_DATE = (SELECT MIN(E2.HIRE_DATE) FROM EMPLOYEE E2 WHERE E1.DEPT_CODE = E2.DEPT_CODE)
AND ENT_YN = 'N';

















































