/*
TCL (TRANSACTION CONTROL LANGUAGE) : 트랜잭션 제어 언어
TRANSACTION : 업무, 처리

변경된 사항을 묶어서 하나의 트랜잭션에 처리
트랜잭션에서 데이터 변경 대상 : INSERT, UPDATE, DELETE (DML)

EX) INSERT INTO -> DB 반영(X)
    INSERT INTO -> COMMIT -> DB 반영(O)
    INSERT INTO 10번 값 추가 -> 1개 트랜잭션에 10개 추가 -> ROLLBACK -> DB 반영(X)
    
1) COMMIT : 메모리 트랜잭션에 임시 저장된 데이터를 DB에 완전히 추가
2) ROLLBACK : 메모리 트랜잭션에 임시 저장된 데이터를 삭제하고, 마지막 COMMIT 상태로 돌아감
3) SAVEPOINT : 메모리 트랜잭션에 저장 지점을 정의
               ROLLBACK을 수행시 전체 작업을 삭제하는 것이 아닌 저장 지점까지만 일부 ROLLBACK
*/

CREATE TABLE DEPARTMENT3 AS SELECT * FROM DEPARTMENT;

SELECT * FROM DEPARTMENT3;

-- 1) COMMIT 예제
INSERT INTO DEPARTMENT3
VALUES ('D0','경리부','L2');

SELECT * FROM DEPARTMENT3;

UPDATE DEPARTMENT3
SET DEPT_TITLE = '전략기획팀', LOCATION_ID = 'L3'
WHERE DEPT_ID = 'D9';

SELECT * FROM DEPARTMENT3;

COMMIT;

ROLLBACK;
SELECT * FROM DEPARTMENT3;

-- 2) ROLLBACK 예제
DELETE FROM DEPARTMENT3
WHERE DEPT_ID = 'D0';

SELECT * FROM DEPARTMENT3;

DELETE FROM DEPARTMENT3
WHERE DEPT_ID ='D9';

SELECT * FROM DEPARTMENT3;

DELETE FROM DEPARTMENT3
WHERE DEPT_ID = 'D8';

ROLLBACK;

-- 3) SAVAPOINT 예제
-- SAVEPOINT 작성해준 후 저장 지점 이름 설정
DELETE FROM DEPARTMENT3
WHERE DEPT_ID = 'D0';

SAVEPOINT "SP1"; -- SP1 이라는 저장 지점 설정

DELETE FROM DEPARTMENT3
WHERE DEPT_ID = 'D9';

SAVEPOINT "AAA"; -- AAA 이라는 저장 지점 설정

DELETE FROM DEPARTMENT3;

SELECT * FROM DEPARTMENT3;

--- AAA까지 롤백
ROLLBACK TO "AAA";
--- SP1까지 롤백
ROLLBACK TO "SP1";

-- 모든 내역 SP1 이전으로 되돌리기
ROLLBACK;

SELECT * FROM DEPARTMENT3;












